FROM node:20-alpine
WORKDIR /src/app
COPY package*.json ./
RUN npm ci
COPY . .

ARG DB_URL
ARG USER_POOL_ID
ARG CLIENT_ID
ARG REGION

ENV DB_URL=$DB_URL
ENV USER_POOL_ID=$USER_POOL_ID
ENV CLIENT_ID=$CLIENT_ID
ENV REGION=$REGION

EXPOSE 3000
CMD ["npm", "run", "start:prod"]
