name: Auth Service CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build Docker image
              run: | 
                docker build \
                --build-arg DB_URL="${{ secrets.DB_URL }}" \
                --build-arg USER_POOL_ID=${{ secrets.USER_POOL_ID }} \
                --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} \
                --build-arg REGION=${{ secrets.REGION }} \
                -t ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest .

            - name: Push Docker image to Docker Hub
              run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest

